version: '3'
services:
  ros-master:
    build: ./rosmaster
    container_name: ros-master
    command:
      - roscore
  web:
    build: ./web
    container_name: web
    ports:
      - "4000:4000"

  rosbridge:
    build: ./rosbridge
    container_name: rosbridge
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    ports:
      - "9090:9090"

  duckiebot:
    build: ./duckiebot
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    
# cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1