version: '3'
services:
  ros-master:
    build: ./rosmaster
    container_name: ros-master
    command:
      - roscore

  rosbridge:
    build: ./rosbridge
    container_name: rosbridge
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    ports:
      - "9090:9090"

  duckiebot:
    build: ./duckiebot
    depends_on:
      - ros-master
    command:
      - roslaunch
      - duckiebot_simulador
      - duckiebot.launch
      - --wait
    environment:
      - ROS_MASTER_URI=http://ros-master:11311

  web:
    build: ./web
    container_name: web
    command:
      - jekyll
      - serve
      - -s
      - /srv/jekyll/duckieweb
    ports:
      - "4000:4000"
    # volumes:
      # - ./temp-web/duckieweb/:/srv/jekyll/duckieweb/